development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: cfreeman
  database: teethtracker_development

test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: cfreeman
  database: teethtracker_test

production:
  adapter: postgresql
